# Generated by Django 5.2.7 on 2025-11-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_done', models.DateField(blank=True, null=True, verbose_name='Дата последнего выполнения')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='Дата следующего выполнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Задача по уходу',
                'verbose_name_plural': 'Задачи по уходу',
                'ordering': ['is_active', 'next_due'],
            },
        ),
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип ухода', max_length=255, unique=True, verbose_name='Тип ухода')),
                ('frequency_days', models.PositiveIntegerField(default=1, help_text='Введите частоту ухода в днях (по умолчанию 1 день)', verbose_name='Частота ухода (в днях)')),
                ('description', models.TextField(blank=True, help_text='Введите рекомендации по типу ухода', null=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, help_text='Отметьте, если это тип ухода по умолчанию', verbose_name='По умолчанию')),
                ('order', models.PositiveIntegerField(default=0, help_text='Укажите порядок отображения типов ухода', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип ухода',
                'verbose_name_plural': 'Типы ухода',
                'ordering': ['order'],
            },
        ),
    ]
