# Generated by Django 5.2.7 on 2025-11-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretask',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='plants.plant', verbose_name='Растение'),
        ),
        migrations.AddField(
            model_name='caretask',
            name='care_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_tasks', to='care.caretype', verbose_name='Тип ухода'),
        ),
    ]
