# Generated by Django 5.2.7 on 2025-11-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretype',
            name='frequency_days',
        ),
        migrations.AddField(
            model_name='caretask',
            name='frequency_days',
            field=models.PositiveIntegerField(default=1, help_text='Введите частоту задачи в днях (по умолчанию 1 день)', verbose_name='Частота задачи (в днях)'),
        ),
    ]
