FROM python:3.11-slim

WORKDIR /app


RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock ./

RUN pip install poetry && poetry config virtualenvs.create false \
    && poetry install --no-dev

COPY . .

RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "tracker.wsgi:application", "--bind", "0.0.0.0:8000"]