# Generated by Django 5.2.7 on 2025-11-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время выполнения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('care_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='care.caretask', verbose_name='Задача по уходу')),
            ],
            options={
                'verbose_name': 'Журнал выполнения ухода',
                'verbose_name_plural': 'Журналы выполнения уходов',
                'ordering': ['-performed_at'],
            },
        ),
    ]
