# Generated by Django 5.2.7 on 2025-11-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareTaskLog',
        ),
    ]
