# Generated by Django 5.2.7 on 2025-11-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя растения', max_length=200, verbose_name='Имя растения')),
                ('species', models.CharField(help_text='Введите вид растения', max_length=200, verbose_name='Вид растения')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение растения', null=True, upload_to='images/plants/user_{user_id}/', verbose_name='Изображение растения')),
                ('notes', models.TextField(blank=True, help_text='Введите заметки о растении', null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'ordering': ['-created_at'],
            },
        ),
    ]
